/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SADLRuntimeModule extends AbstractSADLRuntimeModule {
}
