/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSADLScopeProvider extends DelegatingScopeProvider {
}
