/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SADLUiModule extends AbstractSADLUiModule {

	public SADLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
