/**
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.sadl.tests;

import com.leonardo.lsaf.sadl.sadl.ConnectionMapping;
import com.leonardo.lsaf.sadl.sadl.SadlFactory;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Connection Mapping</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ConnectionMappingTest extends TestCase {

  /**
   * The fixture for this Connection Mapping test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnectionMapping fixture = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static void main(String[] args) {
    TestRunner.run(ConnectionMappingTest.class);
  }

  /**
   * Constructs a new Connection Mapping test case with the given name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConnectionMappingTest(String name) {
    super(name);
  }

  /**
   * Sets the fixture for this Connection Mapping test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected void setFixture(ConnectionMapping fixture) {
    this.fixture = fixture;
  }

  /**
   * Returns the fixture for this Connection Mapping test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConnectionMapping getFixture() {
    return fixture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see junit.framework.TestCase#setUp()
   * @generated
   */
  @Override
  protected void setUp() throws Exception {
    setFixture(SadlFactory.eINSTANCE.createConnectionMapping());
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see junit.framework.TestCase#tearDown()
   * @generated
   */
  @Override
  protected void tearDown() throws Exception {
    setFixture(null);
  }

} //ConnectionMappingTest
