/**
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.sadl.tests;

import com.leonardo.lsaf.sadl.sadl.ContainerInstance;
import com.leonardo.lsaf.sadl.sadl.SadlFactory;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Container Instance</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ContainerInstanceTest extends TestCase {

  /**
   * The fixture for this Container Instance test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContainerInstance fixture = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static void main(String[] args) {
    TestRunner.run(ContainerInstanceTest.class);
  }

  /**
   * Constructs a new Container Instance test case with the given name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ContainerInstanceTest(String name) {
    super(name);
  }

  /**
   * Sets the fixture for this Container Instance test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected void setFixture(ContainerInstance fixture) {
    this.fixture = fixture;
  }

  /**
   * Returns the fixture for this Container Instance test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContainerInstance getFixture() {
    return fixture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see junit.framework.TestCase#setUp()
   * @generated
   */
  @Override
  protected void setUp() throws Exception {
    setFixture(SadlFactory.eINSTANCE.createContainerInstance());
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see junit.framework.TestCase#tearDown()
   * @generated
   */
  @Override
  protected void tearDown() throws Exception {
    setFixture(null);
  }

} //ContainerInstanceTest
