/**
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.sadl.tests;

import com.leonardo.lsaf.sadl.sadl.Enumerator;
import com.leonardo.lsaf.sadl.sadl.SadlFactory;

import junit.framework.TestCase;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Enumerator</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class EnumeratorTest extends TestCase {

  /**
   * The fixture for this Enumerator test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Enumerator fixture = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static void main(String[] args) {
    TestRunner.run(EnumeratorTest.class);
  }

  /**
   * Constructs a new Enumerator test case with the given name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumeratorTest(String name) {
    super(name);
  }

  /**
   * Sets the fixture for this Enumerator test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected void setFixture(Enumerator fixture) {
    this.fixture = fixture;
  }

  /**
   * Returns the fixture for this Enumerator test case.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Enumerator getFixture() {
    return fixture;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see junit.framework.TestCase#setUp()
   * @generated
   */
  @Override
  protected void setUp() throws Exception {
    setFixture(SadlFactory.eINSTANCE.createEnumerator());
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see junit.framework.TestCase#tearDown()
   * @generated
   */
  @Override
  protected void tearDown() throws Exception {
    setFixture(null);
  }

} //EnumeratorTest
