/*
 * generated by Xtext 2.25.0
 */
package com.leonardo.lsaf.sadl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SADLStandaloneSetup extends SADLStandaloneSetupGenerated {

	public static void doSetup() {
		new SADLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
