/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class SADLWebModule extends AbstractSADLWebModule {
}
