/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SADLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/leonardo/lsaf/sadl/parser/antlr/internal/InternalSADL.tokens");
	}
}
