/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.parser.antlr;

import com.google.inject.Inject;
import com.leonardo.lsaf.sadl.parser.antlr.internal.InternalSADLParser;
import com.leonardo.lsaf.sadl.services.SADLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SADLParser extends AbstractAntlrParser {

	@Inject
	private SADLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSADLParser createParser(XtextTokenStream stream) {
		return new InternalSADLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SADLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SADLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
