/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class SADLProposalProvider extends AbstractSADLProposalProvider {
}
