/*
 * generated by Xtext 2.25.0
 */
package com.leonardo.lsaf.sadl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.leonardo.lsaf.sadl.SADLRuntimeModule;
import com.leonardo.lsaf.sadl.SADLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SADLIdeSetup extends SADLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SADLRuntimeModule(), new SADLIdeModule()));
	}
	
}
