/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.ui.tests;

import com.google.inject.Injector;
import com.leonardo.lsaf.sadl.ui.internal.SadlActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SADLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SadlActivator.getInstance().getInjector("com.leonardo.lsaf.sadl.SADL");
	}

}
