<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mediator" nsURI="http://www.leonardo.com/lsaf/sadl/mediator"
    nsPrefix="mediator">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&#xD;&#xA;The mediator model to calculate the automatic layout&#xD;&#xA;of nested ports.&#xD;&#xA;&#xD;&#xA;Year: 2023&#xD;&#xA;Author: Alfa Yohannis&#xD;&#xA;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="MGraph" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//MNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//MEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEdge" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//MConnectableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//MConnectableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MConnectableElement" eSuperTypes="#//MElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MNode" eSuperTypes="#//MConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="algorithm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//MNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//MNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//MEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eastPorts" upperBound="-1"
        eType="#//MPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="westPorts" upperBound="-1"
        eType="#//MPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sadlContainer" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MPort" eSuperTypes="#//MConnectableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfIncomingOutgoingPorts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="side" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="EAST"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subPorts" upperBound="-1"
        eType="#//MPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" eType="#//MNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootPort" eType="#//MPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentPort" eType="#//MPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sadlPort" eType="ecore:EClass http://www.leonardo.com/lsaf/sadl/SADL#//Port"/>
  </eClassifiers>
</ecore:EPackage>
