/**
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.sadl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.leonardo.lsaf.sadl.sadl.SadlPackage#getType()
 * @model
 * @generated
 */
public interface Type extends PackageableElement
{
} // Type
