/*
 * generated by Xtext 2.31.0
 */
package com.leonardo.lsaf.sadl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link SADLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractSADLWebModule extends DefaultWebModule {

}
